### ISSUE TITLE
Naming & Syntax Changes

### ISSUE THREAD

**Issue by shshaw** [steel-scene/steel-scene#1]
As we discussed in Slack, I think it's worth changing the naming to better reflect intentions of each piece.

Here's the HTML breakdown of the syntax I'm proposing based on your Codepen example:

```html
<scene name="boxes">
   
   <transition default duration="1500" easing="Power2.easeOut" />
   <transition name="fast" duration="500" easing="Power3.easeInOut" />
   
   <!-- Use a reference to a transition -->
   <state name="C" default transition="fast">
      <target ref="#box1" x="0" y="0" rotation="0deg" />      
      <target ref="#box2" x="0" y="0" rotation="0deg" />
   </state>
   
   <!-- State specific duration and easing, no <transition> declaration needed -->
   <state name="NE" duration="1000" easing="Cubic.easeInOut" >
      <target ref="#box1" x="100px" y="-100px" rotation="45deg" />      
      <target ref="#box2" x="100px" y="-100px" rotation="45deg" />
   </state>

   ...
   
   <sequence default states="NE,NW,C,SE,SW" duration="3000" />
      
</scene>
```

Then in JS, something like this:

```js
var myScenes = bu.parse(html); // Import and parse the scenes from HTML/JSON.
var myScene = myScenes.scene('boxes'); // Retrieve a specific scene from all the JSON or HTML that's been processed. Alternatively `bu.scene('boxes')`
myScene.transition('NE'); // Uses default `duration` and `easing` unless the `state` has a `duration` and `easing` of its own, or a `transition` reference
myScene.play(); // plays default sequence, or provide it with a name of a sequence
```

**Comment by shshaw** [comment]
May also be worth wrapping any Blue Unicorn HTML in `<template>`

**Comment by notoriousb1t** [comment]
I am a fan of the markup and I am going to run with that.  I am not as much a fan of the JS, though.  I'll update the markup parsers and round robin back to JS and try out a different api approach.

**Comment by shshaw** [comment]
The JS setup is still rough, but the basic workflow would be:
* Parse JSON or HTML ( `bu.parse`, `bu.import`, etc. )
* Retrieve a scene ( `var scene = bu.scene('boxes')` )
* Control the scene directly ( `scene.transition('stateName')` )

It makes more sense to me to deal directly with the scene after parsing versus going through the library to trigger a transition in a scene. In GSAP for example, I don't want to call `TimelineLite.play('myTimeline')`, I'd rather call `myTimeline.play()`.

**Comment by shshaw** [comment]
You can still have methods on the library itself to trigger transitions, but having scenes be an instance with methods to directly control would be more logical to me.

**Comment by notoriousb1t** [comment]
I think that separating parsing HTML and JSON (importHTML, importJSON)  is a better design for importingfrom an API perspective.

I have no issue with creating controllers for the scenes.  I think that it would be better to stay away from .play() though.  The playing is a side effect of changing states.

**Comment by notoriousb1t** [comment]
That being said, if it comes to developer experience vs api exactness, I would rather have a better developer experience.

**Comment by shshaw** [comment]
Yeah, I haven't started thinking much further down the line for the actual control mechanisms yet.

**Comment by notoriousb1t** [comment]
Alright, HTML/JSON and associated code is updated 😄   I have an updated example here: http://codepen.io/notoriousb1t/pen/42361efe3ab940e0ddb905a0e2f39492?editors=1010

I didn't implement the sequences yet because I think that the JavaScript API will inform us how sequences/timelines should be handled.

**Comment by Martin-Pitt** [comment]
Generally per the Custom Elements spec, they should be hyphenated to contrast it against native or fully standardised HTML elements. Not to mention other frameworks.

A-Frame has: `<a-scene></a-scene>`

I'd recommend coming up with a short vendor prefix to use.
Maybe one of `<u-scene>`, `<b-scene>`, `<ani-scene>`, `<fx-scene>`, `<unicorn-scene>`.
I'm partial to `u-scene` myself.

**Comment by notoriousb1t** [comment]
I definitely think it wouldn't be a bad idea to hyphenate it purely to avoid conflicting with new standardized elements.

**Comment by notoriousb1t** [comment]
@shshaw , what are your thoughts?

**Comment by shshaw** [comment]
Hyphenation, definitely. Leaning toward `<u-scene>`, `<u-state>`, etc, though if you're not married to the Blue Unicorn name, that might affect the 'namespacing' as well.

**Comment by notoriousb1t** [comment]
I have no issue changing the name at this stage, but we should figure it out before we go too much farther.  

I think even if we changed it to blunicorn, u-scene would still be fine.  Do you have any other thoughts on names?

**Comment by shshaw** [comment]
Blunicorn will definitely read as "blun-i-corn", which isn't ideal. Let me open another issue for possible names to keep this thread clean.

**Comment by notoriousb1t** [comment]
@Martin-Pitt, we'll keep this issue open until we figure out if a name change is in order.  Then we can collaborate more on prefixes 😄
