### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by shshaw** [steel-scene/steel-scene#5]
Blue Unicorn is a bit ambiguous. As discussed in #1, a clearer name might help focus the development and self-advertise the functionality.

Spitballing some names:

1. Unimate 
2. Blunicorn
2. Animake
3. Verve
4. Mpel
5. MoveIt
6. MakeItMove (Shorten to MIM?)
6. Kinesis
7. Brio
8. Oomph

I know some of them are taken and/or horrible, but that may help spark an idea.

**Comment by notoriousb1t** [comment]
Agreed, I think something more descriptive is called for.  Here are some other thoughts.

1. Animanic
2. Stage
3. Theatre
4. Skit
5. Motionographer
6. Anigraph

**Comment by shshaw** [comment]
Another idea: _SceneSteel_, as in the scaffolding that builds your scenes.

**Comment by notoriousb1t** [comment]
SceneSteel is ok.  Another one is locomation (locomotion + animation)

**Comment by notoriousb1t** [comment]
I'm not sure if the 👍  is for locomation or for SceneSteel.

What about reversing it: SteelScene or using?  I think the adjective+scene thing would work really well with prefixing:

```html
<s-scene name="boxes">
   <s-transition duration="1500" easing="Power2.easeOut" default />
   <s-state name="C" duration="800" default>
      <s-target ref="#box1" x="0" y="0" border-radius="0" background-color="#333" rotation="0deg" />      
      <s-target ref="#box2" x="0" y="0" border-radius="0" background-color="#333" rotation="0deg" />
   </s-state>
   <s-state name="NE">
      <s-target ref="#box1" x="100px" y="-100px" background-color="#00d1d1" rotation="45deg" />
      <s-target ref="#box2" x="100px" y="-100px" background-color="#00d1d1" rotation="45deg" />
   </s-state>
   <s-state name="NW">
      <s-target ref="#box1" x="-100px" y="-100px" background-color="orange" rotation="-45deg" />
      <s-target ref="#box2" x="-100px" y="-100px" background-color="orange" rotation="-45deg" />
   </s-state>
   <s-state name="SE">
      <s-target ref="#box1" x="100px" y="100px" background-color="purple" rotation="-45deg" />
      <s-target ref="#box2" x="-100px" y="100px" background-color="aqua" rotation="45deg" />
   </s-state>
   <s-state name="SW">
      <s-target ref="#box1" x="-100px" y="100px" background-color="aqua" rotation="45deg" />
      <s-target ref="#box2" x="100px" y="100px" background-color="purple" rotation="-45deg" />
   </s-state>
</s-scene>
```

**Comment by notoriousb1t** [comment]
As talked about offline, we are going to go with SteelScene.  I will start working on moving the repos and such.

**Comment by notoriousb1t** [comment]
I have updated the repos and npm targets to "steel-scene".  The global is ```steel``` and the prefix for elements is s-.

If we come up with a better name later, we can change it then. Otherwise I think we are ready to get building.
