### ISSUE TITLE
API Expansions

### ISSUE THREAD

**Issue by notoriousb1t** [steel-scene/steel-scene#7]
From slack discussion on the animation at work slack

```js
const quickTransition = new steel.Transition({
    duration: 350,
	easing: 'ease-in'
});

const initialState = new steel.State({
	transition: quickTransition,
	targets: [
	   { ref: '#id', opacity: 0 }
	]
});

const boxesScene = new steel.Scene('boxes', {
	duration: 1000,
	defaultState: initialState,
        states: {
             default: initialState
        }
});

// walking up the chain
const shouldBeZero = steel
    .scene('boxes')
    .state('default')
    .target('#id')
    .opacity;

// direct usage
initialState.target('#id').opacity;

// import from json/html
new steel.Scene().importFromJSON({ })
new steel.Scene().importFromHTML('#animations');
```

**Comment by notoriousb1t** [comment]
From slack discussion, we need to swap the roles of targets and states and keep track of state per component.

```
const scene = new steel.Scene({ 
	duration: 200,
	defaultState: 'default', // maybe use 'default' implicitly if not specified
});

const logoTarget = new steel.Target('initial', {
	states: {
		default: { scale: 1,   rotate: 0 },
		hover:   { scale: 1.2, rotate: 10 } 
	}
});

scene.addTarget(logoTarget); 

/// meanwhile in an eventhandler....
scene.transition('hover'); // to go to hover state
scene.transition('default'); // to go to default state
```

**Comment by shshaw** [comment]
This does make the usage of scenes and states slightly more confusing, since state names have to be coordinated across targets. Might need to think through this a bit more.

**Comment by shshaw** [comment]
To clarify a bit more and to think 'out loud': 
The core functionality is focused around triggering state transitions in a scene. Hiding the states within a target obfuscates that a bit, especially when coordinating multiple targets with different values in the same state.

With a target-centered approach, it becomes more like DOM event listeners which isn't a bad thing. Basically behaving like `target.on('myState', { scale: 1.2 })` and the scene delegates those events to its children; `scene.trigger('myState')` cascading down the targets.

**Comment by notoriousb1t** [comment]
I think it is about the same in that regard because before the target refs would have to be kept the same to coordinate across states in our current API.

**Comment by notoriousb1t** [comment]
That was exactly my thinking.  A scene would cascade to each target. If a target doesn't have the state would ignore it.  I think this would also work better if we decided to allow targets to have more than one state

**Comment by shshaw** [comment]
Thinking about a target centered approach more like events and pubSub style APIs makes sense to me. A jQuery-like API for targets may even be helpful.

```js
const scene = new steel.Scene(...);

const logo = new steel.Target('#logo', { 
  states: { 
     hover: { scale: 1.2, rotate: 10 }
  }
});
const logoBg = new steel.Target('#logoBg', { 
  states: { 
     hover: { scale: 0.8, rotate: -10 }
  }
});

scene.add(logo,logoBg);
```

I'm not quite sure how, but I'd love for an easy way to add a common state to both targets. Here's a rough draft:

```js
const both = new steel.Target([logo, logoBg], {
  states: {
    default: { scale: 1, rotate: 0 }
  }
});
```

**Comment by notoriousb1t** [comment]
From our conversation on slack

```js
const logo = steel('#logo')
  .on('default',{ scale: 1 })
  .on('hover', { scale: 1.2 });

const logo2 = steel('#logo2')
  .on('default',{ scale: 1 })
  .on('hover', { scale: 1.4 })
  .on('with-param', (ctx, opts) => ({ /* opt specific stuff*/ }));

const scene = steel.scene(logo, logo2);

scene.transition('hover');
// OR
logo.transition('hover');
logo2.transition('hover', { /* options */ }, [ opts ]);
```

**Comment by shshaw** [comment]
Yes, a jQuery-like API where targets are the focus and scenes become more like groups feels like the right approach.

**Comment by shshaw** [comment]
The overall theme of these changes is:
* `target`s are now the main focus of the API.
* A `target` has multiple `states` that are `transition`ed between.
* `transitions` to a `state` can be triggered on a target, or by cascading down from a parent `scene`.
* `scene`s become more like a container or group, allowing control of multiple distinct `target`s 
* A chainable, jQuery-like API to make it easy to add states, trigger transitions, etc.

**Comment by notoriousb1t** [comment]
I think I have captured the spirit of this in the last release 0.7.0
